added app
dominguesgabe/bootcamp-markee-code-review pull request #1
Opened 2023-09-01 00:54 UTC by dominguesgabe

2023-09-01 12:12 UTC, RafaelC457ro requested changes
Alguns sugestões sobre a organização de arquivos:
pastas:
**components**: conterá todos os components do projeto, desde maiores como o sidebar
e menores.
**icons|assets**: contém as images e icons, que podem ser exportados via index.ts.
**utils**: ta ok, tem que conter as funções que não são components.
sobre components maiores:
Sidebar:
Sidebar é um componente que deveria estar dentro da pasta componentes, como uma pasta individual, contendo:
index.ts - exporta Sidebar
Sidebar.tsx - código
Styles.tsx - contém os mini components do styled referente apenas o sidebar

O mesmo se aplica ao MainContent.
Os outros estilos deveriam ser arquivos separados, dentro da pasta components.
No geral em termos de código está bom.

2023-09-01 12:12 UTC, RafaelC457ro commented on .editorconfig
> +insert_final_newline = false
```suggestion
insert_final_newline = true
```
Seria interessante ter esse valor como true, isso é mais cosmético, porém é uma configuração comum em vários projetos, o plugin [Editor config](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) instalado no seu vscode, para adicionar uma linha no final do arquivo evitar o que aconteceu no arquivo abaixo.

2023-09-01 12:12 UTC, RafaelC457ro commented on README.md
> +Markdown writer and reader using React
Seria interessante um README mais populado, breve descrição do que se trata, author, com instruções de como rodar localmente, link do projeto no ar e etc

2023-09-01 12:12 UTC, RafaelC457ro commented on src/app-styles.tsx
> +
```suggestion
```

2023-09-01 12:12 UTC, RafaelC457ro commented on src/app-styles.tsx
> +
```suggestion
```

Estou vendo vários linhas vazias, seria interessante talvez ter um formatter como o https://prettier.io/
e instalar o extenção do vscode ou/e ter um comando para formatar o código em linha de comando, ainda outros projetos configuram o [husky](https://typicode.github.io/husky/) pra rodar a formatação no pré-commit, você pode considerar isso como um caso de estudo.

2023-09-01 12:12 UTC, RafaelC457ro commented on src/react-app-env.d.ts
> +/// <reference types="react-scripts" />
esse arquivo pode ser removido

2023-09-01 12:12 UTC, RafaelC457ro commented on src/resources/files/UseFiles.ts
> +import {
o nome corre para esse aquivo seria useFIles, O capital case é usado apenas para componentes.

2023-09-01 12:12 UTC, RafaelC457ro commented on src/utils/FileObject.ts
> +import { StatusProps } from 'types/AppTypes'
arquivos que não são components é interessante ser camelCase.

2023-09-01 12:12 UTC, RafaelC457ro commented on src/utils/Storage.ts
> +export const GetStoredFiles = async (setFiles: Dispatch<SetStateAction<FileProps[]>>) => {
```suggestion
export const getStoredFiles = async (setFiles: Dispatch<SetStateAction<FileProps[]>>) => {
```

funcões que não são componentes devem ser camelCase

2023-09-01 12:12 UTC, RafaelC457ro commented on src/utils/Storage.ts
> +export const StoreFiles = async (files: FileProps[]) => {
```suggestion
export const storeFiles = async (files: FileProps[]) => {
```

2023-09-01 12:12 UTC, RafaelC457ro commented on src/utils/UtilFiles.ts
> +export const InactivateFiles = (files: FileProps[]) => files.map(file => ({ ...file, active: false }))
```suggestion
export const inactivateFiles = (files: FileProps[]) => files.map(file => ({ ...file, active: false }))
```

2023-09-01 12:12 UTC, RafaelC457ro commented on src/utils/UtilFiles.ts
> +export const ActivateClickedFile = (fileId: string, files: FileProps[]) => {
```suggestion
export const activateClickedFile = (fileId: string, files: FileProps[]) => {
```

2023-09-01 12:12 UTC, RafaelC457ro commented on src/app-styles.tsx
> +    font-family: DM Sans;
```suggestion
    font-family: 'DM Sans', sans-serif;
```
é uma boa prática especificar o tipo da serifa da fonte, visto que em caso de o user bloquear novas fontes o browser vai usar alguma sans-serif padrão.

2023-09-01 12:12 UTC, RafaelC457ro commented on src/app-styles.tsx
> +    font-family: Inconsolata;
```suggestion
    font-family: Inconsolata , sans-serif;
```

2023-09-01 12:12 UTC, RafaelC457ro commented on src/app.tsx
> +import { AppWrapper } from 'app-styles'
O nome de app deveria ser App.tsx visto que é um componente também.

2023-09-05 00:33 UTC, dominguesgabe commented on README.md
> +Markdown writer and reader using React
Corrigido

2023-09-05 00:45 UTC, dominguesgabe commented on src/utils/UtilFiles.ts
> +export const ActivateClickedFile = (fileId: string, files: FileProps[]) => {
Mano tem umas coisas que ele tá pedindo pra ser Upper 
![image](https://github.com/dominguesgabe/bootcamp-markee-code-review/assets/46696299/d6061f8e-55dd-4086-a452-98fb2ad5cae6)

2023-09-15 13:49 UTC, RafaelC457ro commented on src/components/mainContent/MainContent.tsx
> +import {
Renomear a Pasta para MainContent.tsx

2023-09-15 13:51 UTC, RafaelC457ro commented on src/components/sidebar/FileItem.tsx
> +import { FileTextIcon } from 'icons'
Seria interessante cada FileItem ter a sua propria pasta, ou ser um arquivo standalone na pasta components separado do Sidebar

2023-09-15 13:52 UTC, RafaelC457ro commented on src/components/sidebar/Sidebar.tsx
> +import { AddFileButton } from 'components/appStyles'
Renomear a pasta para Sidebar, e mover os outros components para a pas camponents execto o Styles.tsx

2023-09-15 13:53 UTC, RafaelC457ro commented on src/components/appStyles.tsx
> +import { styled, css } from 'styled-components/macro'
renomear para AppStyles.tsx ou só Styles e mover para raiz do App.tsx

2023-09-15 13:53 UTC, RafaelC457ro commented on src/utils/useFiles.ts
> +import {
useFiles é um hook, criar um pasta chamada hooks e mover para lá

2023-09-15 13:54 UTC, RafaelC457ro commented on src/utils/FileObject.ts
> +import { StatusProps } from 'types/appTypes'
Renomear os arquivos para camelCase, pois não se trata de um componente.

2023-09-15 13:54 UTC, RafaelC457ro commented on src/utils/SvgIcons.ts
> +export { ReactComponent as AddFileIcon } from 'ui/add-file.svg'
remover esse arquivo já existe o index.ts das pasta icons

2023-10-03 22:22 UTC, RafaelC457ro reviewed
FileItem e Status deveriam cada um tem a sua pastadinha com seu index.ts
![Captura de Tela 2023-10-03 às 19 09 41](https://github.com/dominguesgabe/bootcamp-markee-code-review/assets/11356651/1d161d82-b785-42fc-90fb-6ee5089551fc)
Styles dentro da pasta do componente deve conter apenas os componentes que são diretamente relacionado ao Item em que ele está composto nesse caso Sidebar, se FileItem usa ListingFileItem, ele deveria ter o seu próprio Styles.tsx 
![IMAGE 2023-10-03 19:21:50](https://github.com/dominguesgabe/bootcamp-markee-code-review/assets/11356651/5d714b3c-4424-4f54-806a-83998039ff54)

2023-10-03 22:22 UTC, RafaelC457ro commented on src/types/appTypes.ts
> +export type genericProps = {
Nome de tipos devem ser CamelCase

2023-10-03 22:22 UTC, RafaelC457ro commented on src/@types/styled.d.ts
> +export {}
Remover

2023-10-05 00:31 UTC, merged